[binaries]
c     = 'arm-none-eabi-gcc'
ar    = 'arm-none-eabi-ar'
strip = 'arm-none-eabi-strip'

[host_machine]
system     = 'none'
cpu_family = 'arm'
cpu        = 'arm'
endian     = 'little'

[properties]
c_args = ['-mcpu=cortex-m4',
          '-mthumb']

c_link_args = ['-nostdlib', '-lgcc']